---

- hosts: all
  tasks:
    - name: configure mysql-cluster yum repository
      yum_repository:
        name: mysql-cluster
        description: MySQL Cluster Yum Repository
        baseurl: file:///opt/mysql-cluster-repo
        enabled: 1
        gpgcheck: no

- hosts: all
  roles:
    - mysql-cluster
